IF NOT EXISTS (SELECT * FROM SYS.DATABASES WHERE NAME = 'DataWareHouseAW2')
BEGIN
  CREATE DATABASE DataWareHouseAW2;
END;
GO

USE DataWareHouseAW2
GO 

IF NOT EXISTS (SELECT * FROM SYS.SCHEMAS WHERE NAME = 'edw')
BEGIN
  EXEC('CREATE SCHEMA edw');
END;
GO

--			CREATE THE edw TABLES

DROP TABLE IF EXISTS edw.FactSALES;
DROP TABLE IF EXISTS edw.DimDATE;
DROP TABLE IF EXISTS edw.DimCUSTOMER;
DROP TABLE IF EXISTS edw.DimEMPLOYEE;
DROP TABLE IF EXISTS edw.DimTERRITORY;
DROP TABLE IF EXISTS edw.DimPRODUCT;

CREATE TABLE edw.DimDATE (
	D_ID INT PRIMARY KEY,
	[Date] DATE NOT NULL,
	[Day] SMALLINT NOT NULL,
	[Month] SMALLINT NOT NULL,
	[Year] SMALLINT NOT NULL,
    [MonthName] NVARCHAR(9),
	[Week] SMALLINT NOT NULL,
	[Quarter] SMALLINT NOT NULL,
	[WeekDay] NVARCHAR(10),
	CONSTRAINT CK_Day CHECK ([Day] > 0 AND [Day] <= 31),
	CONSTRAINT CK_Month CHECK ([Month] > 0 AND [Month] <= 12),
	CONSTRAINT CK_Year CHECK ([Year] > 0)
	
)

DECLARE @STARTDATE DATE;
DECLARE @ENDDATE DATE;

SET @STARTDATE = '2000-01-01'
SET @ENDDATE = DATEADD(YEAR, 100, @STARTDATE)

TRUNCATE TABLE edw.DimDATE
WHILE @STARTDATE <= @ENDDATE
	BEGIN
		INSERT INTO edw.DimDATE
				   (D_ID, [Date], [Day], [Month], MonthName, Week, Quarter, [Year], WeekDay)
			SELECT
				CONVERT(CHAR(8), @STARTDATE, 112) AS D_ID,
				@STARTDATE AS [Date],
				DATEPART(DAY, @STARTDATE) AS [Day],
				DATEPART(MONTH, @STARTDATE) AS [Month],
				DATENAME(MONTH, @STARTDATE) AS MonthName,
				DATEPART(WEEK, @STARTDATE) AS Week,
				DATEPART(QUARTER, @STARTDATE) AS Quarter,
				DATEPART(YEAR, @STARTDATE) AS [Year],
				DATENAME(WEEKDAY, @STARTDATE) AS WeekDay
		SET @STARTDATE = DATEADD(DD, 1, @STARTDATE)
	END

CREATE TABLE edw.DimCUSTOMER (
	C_ID INT IDENTITY (1, 1) PRIMARY KEY,
	Customer_ID INT NOT NULL,
	Ctype CHAR(2) NULL,
	FullName NVARCHAR (50) NULL
)

CREATE TABLE edw.DimEMPLOYEE (
	E_ID INT IDENTITY (1, 1) PRIMARY KEY ,
	Employee_ID INT NOT NULL,
	Fullname NVARCHAR (50) NULL,
	Age TINYINT NULL,
	Gender CHAR(1),
	Title NVARCHAR(50) NULL
)


CREATE TABLE edw.DimPRODUCT (
	P_ID INT IDENTITY (1, 1) PRIMARY KEY ,
	Product_ID INT NOT NULL,
	Pname NVARCHAR (50) NULL,
	Category NVARCHAR (50) NULL
)

CREATE TABLE edw.DimTERRITORY (
	T_ID INT IDENTITY (1, 1) PRIMARY KEY,
	Territory_ID INT NOT NULL,
	TName NVARCHAR (50) NULL,
	Countrycode NVARCHAR (3) NULL,
	Region NVARCHAR (50) NULL
)

CREATE TABLE edw.FactSALES (
	Order_ID INT,
	C_ID INT,
	P_ID INT,
	E_ID INT,
	T_ID INT,
	D_ID INT,
	Total MONEY NOT NULL ,
	Discount FLOAT NOT NULL ,
	Quantity SMALLINT NOT NULL ,
	
	CONSTRAINT PK PRIMARY KEY (Order_ID,C_ID,P_ID,E_ID,T_ID,D_ID),
	CONSTRAINT FK_DATE FOREIGN KEY ( D_ID ) REFERENCES edw.DimDATE ( D_ID ),
	CONSTRAINT FK_EMPLOYEE FOREIGN KEY ( E_ID ) REFERENCES edw.DimEMPLOYEE ( E_ID ),
	CONSTRAINT FK_DimCUSTOMER FOREIGN KEY ( C_ID ) REFERENCES edw.DimCUSTOMER ( C_ID ),
	CONSTRAINT FK_DimTERRITORY FOREIGN KEY ( T_ID ) REFERENCES edw.DimTERRITORY ( T_ID ),
	CONSTRAINT FK_DimPRODUCT FOREIGN KEY ( P_ID ) REFERENCES edw.DimPRODUCT ( P_ID ),
	CONSTRAINT CK_Quantity CHECK (Quantity > 0),
	CONSTRAINT CK_Discount CHECK (Discount >= 0 AND Discount <= 100)
)


--			CREATE THE stage TABLES

IF NOT EXISTS (SELECT * FROM SYS.SCHEMAS WHERE NAME = 'stage')
BEGIN
  EXEC('CREATE SCHEMA stage');
END;
GO

/*			CREATE DimCUSTOMER TABLE			*/
DROP TABLE IF EXISTS stage.DimCUSTOMER;
CREATE TABLE stage.DimCUSTOMER (
	Customer_ID INT PRIMARY KEY,
	Ctype CHAR(2) NULL,
	FullName NVARCHAR (50) NULL,
	FirstName NVARCHAR (50) NULL,
	LastName NVARCHAR (50) NULL
)

/*			CREATE DimEMPLOYEE TABLE			*/
DROP TABLE IF EXISTS stage.DimEMPLOYEE;
CREATE TABLE stage.DimEMPLOYEE (
	Employee_ID INT PRIMARY KEY,
	FullName NVARCHAR (50) NULL,
	FirstName NVARCHAR (50) NULL,
	LastName NVARCHAR (50) NULL,
	BirthDate DATE NULL,
	Age TINYINT NULL,
	Gender CHAR(1),
	Title NVARCHAR(50) NULL
)

/*			CREATE DimPRODUCT TABLE			*/
DROP TABLE IF EXISTS stage.DimPRODUCT;
CREATE TABLE stage.DimPRODUCT (
	Product_ID INT PRIMARY KEY,
	Pname NVARCHAR (50) NULL,
	Category NVARCHAR (50) NULL
)

/*			CREATE DimTERRITORY TABLE			*/
DROP TABLE IF EXISTS stage.DimTERRITORY;
CREATE TABLE stage.DimTERRITORY (
	Territory_ID INT PRIMARY KEY,
	TName NVARCHAR (50) NULL,
	Countrycode NVARCHAR (3) NULL,
	Region NVARCHAR (50) NULL
)

/*			CREATE FactSALES TABLE			*/
DROP TABLE IF EXISTS stage.FactSALES;
CREATE TABLE stage.FactSALES (
	Customer_ID INT NULL ,
	Product_ID INT NULL ,
	Employee_ID INT NULL ,
	Territory_ID INT NULL ,
	Order_ID INT NULL,
	OrderDate DATE NULL,
	C_ID INT NULL ,
	P_ID INT NULL ,
	E_ID INT NULL ,
	T_ID INT NULL ,
	D_ID INT NULL ,
	Total MONEY NULL ,
	Discount FLOAT NULL ,
	Quantity SMALLINT NULL ,
) 